sudo: required

language: java

jdk: openjdk8

services:
  - docker

env:
  - NXF_VER=0.25.6 PROFILE=singularity TEST=ALL TOOL_INSTALL=all SGT_VER=2.4.1

install:
  - sudo apt-get install squashfs-tools
  - "./scripts/travis-install.sh --tool $TOOL_INSTALL"
  - ./scripts/setup_testdata.sh

script:
  - "./scripts/travis-test.sh"
