sudo: required

language: java

jdk: openjdk8

services:
  - docker

env:
  - NXF_VER=0.25.6 PROFILE=singularity SGT_VER=2.4.1
  - NXF_VER=0.25.6 PROFILE=docker      SGT_VER=2.4.1

matrix:
  allow_failures:
    - env: NXF_VER=0.25.6 PROFILE=docker


install:
  - sudo apt-get install squashfs-tools
  - ./scripts/travis-install.sh
  - ./scripts/setup_testdata.sh

script:
  - "./scripts/travis-test.sh"
