sudo: required

language: java

jdk: openjdk8

services:
  - docker

env:
  - NXF_VER=0.25.6 PROFILE=singularity TOOL_INSTALL=all      SGT_VER=2.4.1
  - NXF_VER=0.25.6 PROFILE=docker      TOOL_INSTALL=nextflow

install:
  - sudo apt-get install squashfs-tools
  - "./scripts/travis-install.sh --tool $TOOL_INSTALL"
  - ./scripts/setup_testdata.sh

script:
  - "PROFILE=$PROFILE ./scripts/travis-test.sh"
